
---
- hosts: all
  remote_user: pi
  tasks:
    - name: mount music partition
      mount:
        fstype: ext4
        opts: defaults,noatime
        path: /var/lib/mpd/music
        state: mounted
        src: 'PARTUUID=0c47fa80-05'
      become: yes
    - name: update mpd
      command: mpc update


...
