---
- hosts: all
  remote_user: pi
  tasks:
    - name: change password
      user:
        name: pi
        password: $6$Q1/azKlDyAZrQO6$NKOhziJTt4/4WHsS/DZKD0ZCL5GnYkV.hZLM.rrlOS5qhcxwk.JTVxB.A0o5BLugg5KavnJqKDy6PnE70v8t0.
        update_password: always
      become: yes
...                           
