---
- hosts: all
  remote_user: pi
  tasks:
    - name: copy template asound.conf to jb
      copy:
        src: ./asound_template_35mm.conf
        dest: /etc/asound.conf
        force: no
      become: yes
    - name: copy template mpd.conf to jb
      copy:
        src: ./mpd_template.conf
        dest: /etc/mpd.conf
        backup: yes
        force: yes
      become: yes
    - name: restart mpd
      systemd:
        name: mpd
        state: restarted
      become: yes
...
